Pk/stamina points
Artur-Ws/Swords pull request #31
Opened 2023-04-30 12:55 UTC by PKurowski93

2023-04-30 21:14 UTC, Artur-Ws requested changes
Looks good, as you mentioned it will be good to make some dependencies for stamina, like:
heavier attack -> consumes more stamina
heavier weapon -> consumes more stamina
greater strength attribute -> consumes more stamina
add some attribute for stamina to character, example: each point of this attribute player gets +5 max stamina and +2 stamina regen

Just some ideas for the future, at this point this looks good for me

2023-04-30 21:14 UTC, Artur-Ws commented on main/character.py
> +        if self.stamina_check() == True:
In this case `self.stamina_check()` returns `bool` value, so there is no need to compare this
```suggestion
        if self.stamina_check():
```

2023-05-05 20:02 UTC, patwys approved these changes
Lots of work has been done!
As a framework for further developing looks nice to me.

2023-05-07 17:51 UTC, Artur-Ws approved these changes

2023-05-07 18:09 UTC, merged