Pk/armor points
Artur-Ws/Swords pull request #50
Opened 2023-05-23 21:07 UTC by PKurowski93

#23 Issues

2023-05-24 12:50 UTC, patwys requested changes

2023-06-21 08:59 UTC, patwys commented
I'm approving because you made suggested changes in PR #48 [Implement types of attack in fight module]

2023-06-21 08:59 UTC, patwys approved these changes, later dismissed

2023-06-27 19:30 UTC, Artur-Ws approved these changes, later dismissed

2023-06-27 21:35 UTC, Artur-Ws approved these changes

2023-06-28 04:13 UTC, merged