Pw/button
Artur-Ws/Swords pull request #7
Opened 2023-04-14 12:51 UTC by patwys

Basic buttons.
Folder button - with class button. (Methods: update - puts buttons on screen, check for input - checks if mouse is in range of button, change color - checks if mouse is range of button and chages color if so)
Folder button_main_menu - with surface, position, text and methods for buttons on main menu

2023-04-16 11:00 UTC, Artur-Ws requested changes
Code looks good, it is only suggestion to make button more universal

2023-04-17 18:08 UTC, patwys commented on gui/button.py
> +            self.text = self.__button_font.render(self.text_input, True, "white")
Great idea, thanks! I've corrected it like you suggested.

2023-04-17 19:44 UTC, Artur-Ws approved these changes

2023-04-19 09:24 UTC, cichyc123 approved these changes

2023-04-19 14:27 UTC, merged